[build]
  publish = "." 
  command = "echo 'No build required'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src * data:;"
    X-Frame-Options = "DENY"